# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: qa.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08qa.proto\x12\x05qa.v1\"\xaa\x01\n\x15SearchQuestionRequest\x12\x18\n\x07\x61gentId\x18\x01 \x01(\x03R\x07\x61gentId\x12\x1a\n\x08question\x18\x02 \x01(\tR\x08question\x12\x1a\n\x08qgroupId\x18\x03 \x03(\tR\x08qgroupId\x12\x12\n\x04size\x18\x04 \x01(\x03R\x04size\x12+\n\x06\x66ilter\x18\x05 \x01(\x0b\x32\x13.qa.v1.EntityFilterR\x06\x66ilter\">\n\x0c\x45ntityFilter\x12\x16\n\x06search\x18\x01 \x01(\x08R\x06search\x12\x16\n\x06\x66ilter\x18\x02 \x01(\x08R\x06\x66ilter\"n\n\x13SearchQuestionReply\x12\x12\n\x04\x63ode\x18\x01 \x01(\x03R\x04\x63ode\x12\x18\n\x07message\x18\x02 \x01(\tR\x07message\x12)\n\tquestions\x18\x03 \x03(\x0b\x32\x0b.qa.v1.QuesR\tquestions\"T\n\x04Ques\x12\x1a\n\x08qgroupId\x18\x01 \x01(\tR\x08qgroupId\x12\x1a\n\x08question\x18\x02 \x01(\tR\x08question\x12\x14\n\x05score\x18\x03 \x01(\x01R\x05score2V\n\x06Search\x12L\n\x0eSearchQuestion\x12\x1c.qa.v1.SearchQuestionRequest\x1a\x1a.qa.v1.SearchQuestionReply\"\x00\x42\x1cZ\x1atest-analysis/api/qa/v1;v1b\x06proto3')



_SEARCHQUESTIONREQUEST = DESCRIPTOR.message_types_by_name['SearchQuestionRequest']
_ENTITYFILTER = DESCRIPTOR.message_types_by_name['EntityFilter']
_SEARCHQUESTIONREPLY = DESCRIPTOR.message_types_by_name['SearchQuestionReply']
_QUES = DESCRIPTOR.message_types_by_name['Ques']
SearchQuestionRequest = _reflection.GeneratedProtocolMessageType('SearchQuestionRequest', (_message.Message,), {
  'DESCRIPTOR' : _SEARCHQUESTIONREQUEST,
  '__module__' : 'qa_pb2'
  # @@protoc_insertion_point(class_scope:qa.v1.SearchQuestionRequest)
  })
_sym_db.RegisterMessage(SearchQuestionRequest)

EntityFilter = _reflection.GeneratedProtocolMessageType('EntityFilter', (_message.Message,), {
  'DESCRIPTOR' : _ENTITYFILTER,
  '__module__' : 'qa_pb2'
  # @@protoc_insertion_point(class_scope:qa.v1.EntityFilter)
  })
_sym_db.RegisterMessage(EntityFilter)

SearchQuestionReply = _reflection.GeneratedProtocolMessageType('SearchQuestionReply', (_message.Message,), {
  'DESCRIPTOR' : _SEARCHQUESTIONREPLY,
  '__module__' : 'qa_pb2'
  # @@protoc_insertion_point(class_scope:qa.v1.SearchQuestionReply)
  })
_sym_db.RegisterMessage(SearchQuestionReply)

Ques = _reflection.GeneratedProtocolMessageType('Ques', (_message.Message,), {
  'DESCRIPTOR' : _QUES,
  '__module__' : 'qa_pb2'
  # @@protoc_insertion_point(class_scope:qa.v1.Ques)
  })
_sym_db.RegisterMessage(Ques)

_SEARCH = DESCRIPTOR.services_by_name['Search']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\032test-analysis/api/qa/v1;v1'
  _SEARCHQUESTIONREQUEST._serialized_start=20
  _SEARCHQUESTIONREQUEST._serialized_end=190
  _ENTITYFILTER._serialized_start=192
  _ENTITYFILTER._serialized_end=254
  _SEARCHQUESTIONREPLY._serialized_start=256
  _SEARCHQUESTIONREPLY._serialized_end=366
  _QUES._serialized_start=368
  _QUES._serialized_end=452
  _SEARCH._serialized_start=454
  _SEARCH._serialized_end=540
# @@protoc_insertion_point(module_scope)
